### ISSUE TITLE
Huge import log

### ISSUE THREAD

**Issue by mktums** [Yuego/django-fias#16]
Thousands of "Out of date entry. Skipping..." entries in full import log.

There's two possible ways to resolve it:
1. Using logging options (levels of messages)
2. Write custom logger class which will use :
   * `chr(8)` to minimize output, but leaving it realtime.
   * counters & last recieved error for stackable items, e.g. `Skipped 187 outdated items…`

I can implement second one tomorrow and make a pull request.

PS: Пишу по-английски ради практики :)

**Comment by snikulov** [comment]
А возможно проценовку импорта реализовать? :)
То есть, данные вроде как фиксированны, может какой-нибудь индикатор прогресса вместо логов вида "Out of date entry. Skipping..."

**Comment by Yuego** [comment]
Чтоб сделать проценты, придётся читать файлы целиком. Думаю, большинство серверов сдуются загружать несколько гигов XML в оперативу :)

Есть другой вариант: количество загружаемых файлов известно, известен и их размер. Можно, к примеру, вычислить соотношение размеров и выводить проценты по мере загрузки файлов. Но тогда будет что-то вроде 1%...1%...2%.....................99%, т. к. по сравнению с остальными, ADDROBJ и HOUSE просто огромны.

А можно посчитать среднее кол-во байт на запись в каждом файле (заранее естественно). Делим размер файла на эти байты, получаем приблизительное кол-во записей.

**Comment by snikulov** [comment]
Ну как бы вариант :+1: 
Все лучше, чем пара дней безвестности :)
Что рекомендуете для базы - mysql/mariadb или postgre?

**Comment by Yuego** [comment]
MySQL/MariaDB не умеют делать рекурсивные запросы, поэтому индексация базы происходит очень медленно и требует кучу дополнительного места на диске.
Postgre умеет - базы индексируются сильно быстрее. Плюс в postgresql есть встроенное поле UUID, а в mysql идентификаторы хранятся в обычном char.
В остальном принципиальной разницы нет, но я предпочитаю postgresql.

**Comment by Yuego** [comment]
Решено в ветке develop.
