### ISSUE TITLE
Возможность частичного импорта

### ISSUE THREAD

**Issue by nuklea** [Yuego/django-fias#21]
Дело в том, что команда `./manage.py fias --file fias_xml.rar` выполняется довольно продолжительное время. На данный момент прошло уже больше полутора суток, размер базы привысил 8gb. Все это время утилизация диска зашкаливает (у меня обычные hdd).

А на самом деле мне нужны лишь улицы с домами определенного города. Есть ли такая возможность?

Может открыть группу google для вопросов?

**Comment by Yuego** [comment]
Частично решено через фильтры. См. https://github.com/Yuego/django-fias/commit/f55b18ddb5b930c3fc5049527582304caa12b3cb
