### ISSUE TITLE
Проблемы с новым Sphinxit

### ISSUE THREAD

**Issue by RoobinGood** [Yuego/django-fias#26]
Во views.py у Вас есть хак для исправления бага с сортировкой в Sphinxit. Не так давно этот баг был исправлен. Теперь в этом месте возникает ошибка, по крайней мере у меня. 
Решилось избавлением от u'weight() DESC', но потом возникла проблема с индексацией. В результате черной магии все стало хорошо, однако, обратите внимание )

**Comment by Yuego** [comment]
В новой версии зависимость от sphinxit удалена.
