### ISSUE TITLE
Импорт данных в текущую БД

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#43]
В документации написано, что с пункта 5 рекомендации по установке являются необязательными, т.е. данные не обязательно импортировать в отдельную БД.

При выполнении команды "/manage.py migrate" на тестовом проекте поднимается исключение:

    django.core.exceptions.ImproperlyConfigured: FIAS: database alias `fias` was not found in DATABASES

При разворачивании следовал инструкции, что я делаю не так?

**Comment by Yuego** [comment]
Ошибка в приложении. В ближайшее время поправлю.

Пока, чтоб обойти проблему, добавьте в settings.py строку

FIAS_DATABASE_ALIAS = 'default'

**Comment by jungornti** [comment]
Это сделать я попробовал вчера первым делом:

1. создал пустую базу
2. FIAS_DATABASE_ALIAS = 'default'
3. ./manage migrate

Возникло исключение:

django.db.utils.ProgrammingError: ОШИБКА:  отношение "fias_addrobj" не существует


Переменная DATABASE_ROUTERS закомментирована (не определена).

**Comment by Yuego** [comment]
Какая версия django у вас?

**Comment by jungornti** [comment]
Как в setup.py и описано Django >= 1.5:

Django==1.8.6
-e git+https://github.com/Yuego/django-fias.git@e8ee97f664ccf020f0eba288bb00ea047ffce5c8#egg=django_fias-master
Django-Select2==4.3.2
lxml==3.5.0
psycopg2==2.6.1
rarfile==2.7
six==1.10.0
suds-jurko==0.6
unrar==0.3
wheel==0.24.0

**Comment by Yuego** [comment]
С тем же набором пакетов ошибок во время миграции не возникло (на test_project). Создал новый пустой проект. Без каких-либо настроек миграция так же прошла. БД пробовал: sqlite 3.8.10.2, postgresql 9.4.4.

Обновите django-fias - я кое-что поправил.

**Comment by jungornti** [comment]
После обновления django-fias ошибок миграции не возникло.
