### ISSUE TITLE
Импорт из dbf файлов

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#44]
ФИАС предоставляет дельты и сами базы в формате xml и dbf.

Для python есть утилита dbfread. Она позволяет последовательно, без полной загрузки файла в память считывать данные, автоматически приводить их к нужному типу (даты), работает быстрее и ест меньше памяти.

Работает это всё дело намного быстрее парсинга xml и прочих операций соответственно.

Насколько я понимаю ваш код, переписать его для поддержки dbf вместо xml будет не очень сложно, там действительно очень мало различий - в паре мест убрать валидацию по тегу (row.tag == 'Object', например) и конверсию дат вручную - и вместо dict(row.attrib())  просто возвращать row в bulk index.

У меня есть прототип основанный на частях вашего кода, на моём не очень быстром ПК импорт 1200000 записей из таблицы AddrObj происходит в течение 30-40 минут. Код прототипа пока что выложить не могу к сожалению, т.к. он очень сырой.

**Comment by jungornti** [comment]
А импорт файлов с фильтрацией по, например, коду региона выполняется вообще за считаные минуты и совсем не ест память (так как в памяти хранится всего, например, 20000 адресных объектов)

**Comment by Yuego** [comment]
Есть одна проблема с этим:

dbfread работает с файловой системой и не умеет читать сразу из файлового дескриптора - придётся распаковывать архив во временный каталог. А это несколько гигабайт данных для полного архива. Как вы решили это?

Ну и ещё *.dbf файлы разбиты на части - нужно менять логику импорта таблиц. Хотя это не такая уж большая проблема.

Импорт из XML тоже не ест память в общем-то. Файл читается последовательно прямо из архива и не загружается целиком в память. Сильно больше времени уходит на запись импортированных в БД данных на диск.
Хотя, бесспорно, парсинг dbf должен идти быстрее из-за меньшего оверхеда.

В целом идея мне по душе - нужно только решить что делать с озвученной выше проблемой.

**Comment by Yuego** [comment]
Пока у меня есть одна мысль - перегрузить метод __init__ класса DBF. Но придётся поменять сигнатуру, что не есть хорошо.

**Comment by Yuego** [comment]
В общем, пока пришлось сделать костыль для распаковки архива.
Заодно потестировал скорость импорта (тестил на двух дельта-архивах одной версии):

XML архив: 0:01:39.232584
XML распакованный: 0:01:38.237972
DBF архив: 0:01:19.759927
DBF распакованный: 0:01:17.718422

Из DBF действительно импортируется побыстрее. Даже несмотря на необходимость распаковывать архив. Надо бы проверить, какой разница окажется для полных архивов, да сервис налоговой весь день в отключке. Как-нибудь в другой раз посмотрю.

Если есть желание потестить, переключитесь на ветку new_importer

**Comment by jungornti** [comment]
Добрый день, рад видеть изменения.

На самом распаковка архива (по моему мнению) не является проблемой в 2015 году, особенно, если мы говорим о импорте такой адресной базы, как ФИАС. Пользователь вполне может провести операции по распаковке (если они необходимы) и удалению файлов из временной директории вручную, либо это можно делать автоматически. По поводу большого веса архива и места на диске - в наше время это неактуально, так как диск стоит дешевле чем память и нам доступны большие объёмы хранилищ.

P.S.: я правильно понимаю, что у вас стиль написания кода таков - при определении класса вы в конструкторе объявляете возможные переменные класса, которые могут быть использованы в других методах? Если так, то на мой взгляд это антипаттерн, который увеличивает когнитивную нагрузку читающего код, так как лучше вместо объявления переменной в методе __init__, инициализации её в None и установки её значения в одном из методов, писать чистые функции - те, что принимают какое-то значение, его модифицируют и возвращают.

Вместо:

    class LocalArchiveTableList(TableList):

        def __init__(self, src, version=None):
            self._path = None
            super(LocalArchiveTableList, self).__init__(src=src, version=version)

        def unpack(self):
            self._path = tempfile.mkdtemp()

            self._archive.extractall(self._path)

Можно:

    class LocalArchiveTableList(TableList):

            def unpack(self):
                path = tempfile.mkdtemp()

                self._archive.extractall(path)
                return path

И ещё момент - повсеместно используются "приватные" переменные, начинающиеся с одинарного подчеркивания, что несколько бессмысленно в данной реализации и тоже усложняет чтение кода (на мой взгляд). Например: в классе LocalArchiveTableList объявляется переменная _unpack, значение которой понятно __только__ из контекста окружающего кода. Неплохо было бы назвать эту переменную is_archive_unpacked, тогда контекст сразу переносится в её название и дополнительное обращение к коду, инициализирующему/использующему эту переменную не нужно.

Я понимаю, что в каждой команде может быть свой стиль кодирования, поэтому всё вышенаписанное является только предложением.

**Comment by Yuego** [comment]
> На самом распаковка архива (по моему мнению) не является проблемой в 2015 году, особенно, если мы говорим о импорте такой адресной базы, как ФИАС. Пользователь вполне может провести операции по распаковке (если они необходимы) и удалению файлов из временной директории вручную, либо это можно делать автоматически. По поводу большого веса архива и места на диске - в наше время это неактуально, так как диск стоит дешевле чем память и нам доступны большие объёмы хранилищ.

Проблемой это может стать, если /tmp смонтирован в RAM. Тут, бесспорно, можно придумать обходные маневры, например указывать параметр с путем к временному каталогу. Проблема не принципиальна, но кто-то может с ней столкнуться.

> P.S.: я правильно понимаю, что у вас стиль написания кода таков - при определении класса вы в конструкторе объявляете возможные переменные класса, которые могут быть использованы в других методах? Если так, то на мой взгляд это антипаттерн, который увеличивает когнитивную нагрузку читающего код, так как лучше вместо объявления переменной в методе init, инициализации её в None и установки её значения в одном из методов, писать чистые функции - те, что принимают какое-то значение, его модифицируют и возвращают.

В коде всё просит рефакторинга. Особенно учитывая, что написан он за два вечера прямо из головы.
Привести всё к хотя бы какому-то подобию функционального стиля - следующий шаг. Там ещё очень не хватает тестов.

> И ещё момент - повсеместно используются "приватные" переменные, начинающиеся с одинарного подчеркивания, что несколько бессмысленно в данной реализации и тоже усложняет чтение кода (на мой взгляд). Например: в классе LocalArchiveTableList объявляется переменная unpack, значение которой понятно _только__ из контекста окружающего кода. Неплохо было бы назвать эту переменную is_archive_unpacked, тогда контекст сразу переносится в её название и дополнительное обращение к коду, инициализирующему/использующему эту переменную не нужно.

На самом деле метод unpack и весь сопутствующий ему код - костыль, придуманный на ходу в самый последний момент. Я б с удовольствием от него избавился, но пока не придумал, как это лучше сделать.

А в целом с критикой я согласен. Особенно, учитывая, что давно не могу уделять достаточно времени кодингу и, соответственно, изучению актуальных паттернов и практик. Другие проблемы, другие заботы. IDE запускаю раз в неделю на выходных в качестве хобби.

**Comment by jungornti** [comment]
Однако, у вашего приложения есть пользователи, и это главное. Круто было бы получить поддержку импорта из dbf-формата, так как тогда это можно было бы использовать в наших приложениях. К сожалению, возникнувшие проблемы с версиями, неточностями документации и ошибками конфигурации заставили меня начать писать свой велосипед, основанный на вашем коде, но так как времени реально мало, то проблемы по сути, те же.

Если бы получить версию, которая работает с дбф, использует актуальные версии приложений (django-select2, django 1.8-1.9, например), то можно было бы использовать это в продакшене.

Ну и соответственно, дорабатывать под потребности и делать pull requests. Например, сейчас я использую  django+elasticsearch+ библиотеку django-el индексирую 20к адресов для области, результаты получаются неплохие (пробовал максимум на 600к адресных объектах, но там в силу ограничения моей машины всё работало не очень быстро).

**Comment by Yuego** [comment]
Собственно, оно уже сейчас умеет django-select2 5.3+, django 1.8+, грузить XML, DBF как из архива, так и из каталога с файлами (кстати, dbfread валится с python3.3+, но мой pull request автор уже [принял](https://github.com/olemb/dbfread/pull/11>)), само собой и с fias.nalog.ru умеет само скачивать архивы и импортировать (в т. ч. обновляться инкрементально из дельта-архивов).

Всё это есть в ветке develop. Я слил туда всё, что успел наваять за последнее время. Теперь это  надо бы привести в нормальный вид, покрыть тестами (мечтай, мечтай... :))...

**Comment by jungornti** [comment]
В ближайшее время протестирую импорт из ветки new_importer, о результатах отпишусь =)

**Comment by jungornti** [comment]
Вот такой трейсбек: http://pastebin.com/nkaDZJyf 

Кстати, это действительно необходимо, импортировать нормативные документы? Мне кажется, что основные данные это адресные объекты (addrobj) и словарь сокращений (socrbase).

Вообще, тут получается такая ситуация, что если эти данные вставляются пачкой (bulk), то IntegrityError на уровне инстанса модели вообще не отловить. Хотя вообще не совсем понятно, почему в dbf-таблице "nordoc" имеются документы с повторяющимся идентификатором, по документации о составе данных этой ИС этот идентификатор должен являться уникальным (если рассуждать логически).

**Comment by jungornti** [comment]
Обе таблицы импортировались за 14 минут из файла fias_dbf.xml, успешно, за 14 минут. Остальную часть протестирую завтра - обновление из дельты и тд.

**Comment by Yuego** [comment]
http://pastebin.com/uB77dq4k

Оставлю это здесь. Нужно с этим что-то сделать.

**Comment by jungornti** [comment]
Мне кажется, что это ошибки целостности в БД и такие записи (дублирующиеся) необходимо игнорировать. К тому же, на мой взгляд, ФИАС используется для импорта двух основных таблиц - socrbase и addrobj, т.е. normdoc, house, houseint и тд можно исключить из импорта по-умолчанию, вообще.

**Comment by Yuego** [comment]
> Мне кажется, что это ошибки целостности в БД и такие записи (дублирующиеся) необходимо игнорировать.

Весь вопрос в том, как их игнорировать. Записи добавляются в базу пачками по ~10000 (настраиваемо). Можно попробовать перехватывать исключение, как-то выдергивать из текста ошибки id записи и перебором исключать её из пачки, затем повторно пытаться загрузить в БД.
Но это довольно сильно снизит скорость импорта.

Для MySQL есть INSERT  IGNORE и REPLACE. Для PG есть INSERT ON CONFLICT DO NOTHING (но это только с версии 9.5). У меня уже была мысль написать свой менеджер, который будет выполнять специфичные для БД запросы. Это бы сильно упростило жизнь и не пришлось бы городить костыли. Но универсального метода не существует - в актуальных версиях Postgres нет поддержки нужных функций. Но, можно создать хранимую процедуру... В общем, простого пути нет - нужно над этим подумать как следует.

> К тому же, на мой взгляд, ФИАС используется для импорта двух основных таблиц - socrbase и addrobj, т.е. normdoc, house, houseint и тд можно исключить из импорта по-умолчанию, вообще.

Согласен. Следует поменять поведение по-умолчанию.

**Comment by jungornti** [comment]
По сути, если исходить из специфики проекта, то самое простое решение - это расширить класс BulkIndex и задать ему параметры bulk_size и silent=True, как вариант. И при импорте таблицы normdoc использовать bulk_size=1, и silent=True.

Объясню, почему я так считаю - предметная область FIAS крайне мала и обходится всего несколькими сущностями. Мы знаем, что эта предметная область расширяться не будет. А так как в нашей ситуации основным ограничением является свободное время на реализацию функционала, то этот путь (на мой взгляд) эффективнее, так как писать менеджеры с разной реализацией поведения для разных бекендов, по факту, это как стрельба по воробьям.

Другим решением может быть изменение структуры данных в BulkIndex - документы для индексации хранить не в списке, а например, в set, хешируя по PK, либо для этого просто используя обычный словарь (словарь хуже по расходу памяти).

**Comment by Yuego** [comment]
Уменьшение количества записей сильно замедлит импорт, т. к. будет коммит на каждую запись. Скорость падает на порядок.
Тут даже нет проблемы и необходимости что-то переопределять. Размер пачки записей указывается прямо из командной строки ключом --limit
Можно указать 1, и импорт будет происходить по 1 записи за раз, но, повторюсь, это ооочень медленно.
Самым эффективным способом, я думаю, было бы, все же возложить обработку дублей на плечи БД.

Тут есть ещё другой момент. Я поднял документацию по структуре ФИАС.
AOID - это уникальный идентификатор записи. Он не может повторяться ни при каких условиях.
AOGUID - это уникальный идентификатор адресного объекта. Он всегда соответствует конкретному объекту, но в БД может встречаться сколько угодно раз. 
По полю NEXTID определяется, был ли объект изменён и какая версия актуальна после него. NEXTID указывает на AOID новой версии объекта. Также есть поле PREVID, которое указывает на предыдущую версию объекта в истории (пример для 2-х версий):

Старый объект: AOID=<UUID0> AOGUID=<UUID> NEXTID=<UUID1> PREVID=None
Новый объект: AOID=<UUID1> AOGUID=<UUID> NEXTID=None PREVID=<UUID0>

Так вот, мне кажется, проблема кроется где-то здесь. Какой-то объект потерялся в этой истории - человеческий фактор вряд ли исключается.

Но я не добавлял проверку актуальности объекта. Там есть аж 2 поля: ACTSTATUS и LIVESTATUS. Возможно, если добавить проверки для них, проблема самоликвидируется.

Будем попробовать...

**Comment by jungornti** [comment]
Действительно, ранее я столкнулся с такой же ситуацией в таблице normdoc, причем при импорте из xml всё было в порядке, а из dbf - IntegrityError. Я думаю что это действительно, нарушение целостности данных. К тому же в интернете пишут, что для ФИАС это нормально, как и битые дельта-архивы и так далее. К сожалению.

Согласен, по поводу импорта по 1-й записи, я не обратил внимание что это таблица addrobj.

Как вам вариант с альтернативной структурой данных для BulkIndex - вместо списка использовать set по кастомному хешу для первичного ключа записи - это решит проблему IntegrityError, но надо будет пропускать неактуальные записи в таком случае.

**Comment by Yuego** [comment]
Можно переделать структуру БД в соответствии с документацией. Но это повлечет за собой проблемы с работой с другими таблицами, которые ссылаются на AddrObj через поле AOGUID - ForeignKey уже использовать невозможно в приципе по тем же причинам - потенциально возможные дубли.

> Как вам вариант с альтернативной структурой данных для BulkIndex - вместо списка использовать set по кастомному хешу для первичного ключа записи - это решит проблему IntegrityError, но надо будет пропускать неактуальные записи в таком случае.

Можно поподробнее? Что-то я никак не пойму, о каком BulkIndex идет речь.

**Comment by jungornti** [comment]
Ошибся в названии класса, в master-ветке, речь идёт про fias.importer.BulkCreate. У него есть массив _objects, который можно заменить на dict, либо на set. Но если менять на сет, то для добавляемых объектов надо переопределить __hash__ (если не ошибаюсь), чтобы определять уникальность элемента по первичному ключу.

**Comment by Yuego** [comment]
Теперь понятно. Да, это могло бы быть выходом.
Более того, у моделей django уже есть метод __hash__ с нужным нам функционалом - он возвращает hash от первичного ключа. Так что ничего переопределять и не требуется.

У меня есть немного времени - сейчас попробую применить set и потестить.

**Comment by Yuego** [comment]
Кстати, set не панацея. Вполне может статься так, что дубль попадёт в разные пачки. И снова мы нарываемся на IntegrityError :(

**Comment by Yuego** [comment]
Думаю, эту issue можно закрывать. Импорт из DBF работает корректно. А для обсуждения дублей откроем отельное обсуждение.
