### ISSUE TITLE
Зависимость от mysql

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#46]
Если проект не использует мускуль, и на хосте вообще нет библиотек для работы с ним, то вываливается ошибка использования mysql в django, а происходит это по причине принудительной зависимости fias от mysql (см. fias/config.py - FIAS_SEARCHD_CONNECTION - по-умолчанию mysql).

Это необходимо сделать опциональным, иначе проект вообще не стартует.

**Comment by Yuego** [comment]
Там по сути зависимость не столько от mysql, сколько от sphinx. Приложение использует этот поисковый движок для подбора адресов через AddressField

Хотя ничто не мешает сделать эту зависимость опциональной, а вместе с ней и источник записей для AddressField.

**Comment by jungornti** [comment]
можно это вынести просто в отдельный модуль, абстрагировать интерфейс для

1. индексации данных, будь то таблица в бд, sphinx или индекс в elasticsearch
2. интерфейс для создания запроса в поисковый бэкенд
3. вьюху (опционально)

Ну и по-умолчанию, можно не использовать вообще ничего, либо поиск по БД, например.

**Comment by jungornti** [comment]
У вас по большому то счёту всё готово для этого, надо только чуть отрефакторить код - вынести запрос из вьюхи в бекенд.

**Comment by Yuego** [comment]
Сделал кое-какие наброски в эту сторону (в ветке develop).

По-умолчанию используется бэкенд noop, который всегда возвращает в select2 (AddressField) пустой набор данных. Для сфинкс создал одноименный бэкенд и перенёс туда все связанные с ним функции.

Так же переименовал fias_sphinx в fias_suggest. Функционал команды fias_suggest теперь опеределяется выбранным бэкендом.

**Comment by jungornti** [comment]
Вот это здорово! Как только появится свободное время, постараюсь это протестировать и написать свой бэкенд, по результатам отпишусь. Ну и если всё отлично - за мной пул реквест.
