### ISSUE TITLE
Ошибка при импорте с сайта Fias

### ISSUE THREAD

**Issue by Sky-Cat** [Yuego/django-fias#53]
```
python /usr/local/lib/python2.7/site-packages/fias1/manage.py fias --skip --update
Database updating...
INFO: Downloading file: http://fias.nalog.ru/Public/Downloads/20160728/fias_delta_xml.rar
INFO: Updating table `house` from 278 to 279...
INFO: Fixed wrong BOM header
Out of date entry. Skipping...
Out of date entry. Skipping...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fias1/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/fias/management/commands/fias.py", line 74, in handle
    load_delta_xml(skip=skip)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/commands.py", line 36, in load_delta_xml
    arch.load(truncate=False, skip=skip)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/archive.py", line 137, in load
    ldr.load(truncate=False, update=True)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/loader/base.py", line 71, in load
    _fast_iter(context=context, func=self.process_row)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/loader/base.py", line 14, in _fast_iter
    func(elem)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/loader/house.py", line 34, in process_row
    self._bulk.push(row, related_attrs=related_attrs)
  File "/usr/local/lib/python2.7/dist-packages/fias/importer/bulk.py", line 55, in push
    self.objects.append(self.model(**data))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'divtype' is an invalid keyword argument for this function
```

Параметр --skip не срабатывает, следующая дельта не загружается и не обрабатывается.

```
python --version
Python 2.7.12+

django.VERSION
(1, 8, 4, 'final', 0)
```

**Comment by Yuego** [comment]
После 9 июня этого года, как оказалось, изменились схемы баз ФИАС. Нужно обновить и смигрировать.

Какую версию модуля ФИАС используете? Не уверен, что смогу добавить миграции для 0.x.
А 1.x не включает в себя некоторые функции, и не все идеи реализованы. Хотя импорт работает гораздо лучше. Поддержка sphinx так же реализована, а вот поиск "шаг за шагом" - нет.
Кроме того теперь необходима версия django-select2 не ниже 5.3.0.

Я сделал необходимые изменения в моделях и добавил миграцию под них. Файл, указанный вами, импортируется успешно.

**Comment by Sky-Cat** [comment]
Я пользуюсь вашим замечательным приложением только для импорта данных в MySQL.

Сейчас версия 0.6.1.

Как вы считаете, мне подойдет версия 1.х? Мне нужно импортировать в базу следующие таблицы:

- ADDROBJ
- HOUSE
- NORDOC
- SOCRBASE

**Comment by Yuego** [comment]
Да, для этих целей более чем подойдёт.
Плюс она работает с django 1.9/python3
Я написал в README коротенько про обновление до 1.0.0 через 0.6.2, куда добавил миграцию.
Либо можете поставить с нуля и импортировать - так будет корректнее, т. к. добавленные поля в существующей БД не обновятся никак - только импортировать всю базу по новой.

**Comment by Sky-Cat** [comment]
Спасибо большое за разъяснения. В пятницу буду пробовать обновиться.

**Comment by Sky-Cat** [comment]
Начал потихоньку разбираться с новой версией (python не знаю, к сожалению).

Первая ошибка:
```
File "/usr/local/lib/python2.7/dist-packages/fias/importer/source/archive.py", line 6, in <module>
    from progress.bar import Bar
ImportError: No module named progress.bar
```

Решение:
`pip install progress`

**Comment by Yuego** [comment]
Вы используете pip для установки django-fias? 
Я обновил архив на pypi.

**Comment by Sky-Cat** [comment]
Что-то вообще странное происходит. Через pip устанавливается только версия 0.6.2, хотя версия 1.0 в пакетах присутствует:
```
pip search fias
django-fias (1.0.0)         - FIAS Django integration
  INSTALLED: 0.6.2
  LATEST:    1.0.0
```
По командам
```
pip install django-fias
pip install -U django-fias
pip install django-fias>0.9
```

устанавливается только 0.6.2.

**Comment by Yuego** [comment]
В базе pip нет одной из зависимостей. Я пока вернул старый список. Сейчас всё должно работать как надо.
Пришлось изменить номер версии, т. к. pypi не даёт перезаливать файлы :(
Только вот почему-то pip не видит новую версию, а отображает старую, которой даже на сайте pypi уже нет. Может, глюк какой у них, не знаю.

**Comment by Yuego** [comment]
Попробуйте установить так:

`pip install django-fias --no-cache-dir --upgrade`

**Comment by Sky-Cat** [comment]
Так получилось установить, спасибо.

**Comment by Sky-Cat** [comment]
Всё замечательно установилось, все команды выполнились без ошибок, начался импорт файлов с сайта fias.nalog.ru.

У меня есть несколько вопросов:

1. В каком формате лучше (стабильнее) скачивать обновления баз, xml или dbf?
2. Вы не планируете добавить поддержку таблицы ROOM?

Огромное вам спасибо за такую замечательную программу.

**Comment by Sky-Cat** [comment]
Еще один нюанс. Не знаю, ошибка это или особенность.

Идентификаторы объектов (AOGUID) в xml-файле выглядят так: "afe171a1-6cf4-4de5-9b20-049531501362" - 36 символов, а в базе они сохраняются так: afe171a16cf44de59b20049531501362 - 32 символа.

Мне кажется, это сломает обратную совместимость в рабочих проектах. Например, у нас справочник организаций завязан на id улиц и домов. Там явно указываются идентификаторы адресных объектов.

**Comment by Yuego** [comment]
> В каком формате лучше (стабильнее) скачивать обновления баз, xml или dbf?

В любом. Но DBF весят значительно меньше - быстрее качаются. И импортирует из них чуть быстрее при прочих равных.

> Вы не планируете добавить поддержку таблицы ROOM?

Планирую добавить все справочники.

> Идентификаторы объектов (AOGUID) в xml-файле выглядят так: "afe171a1-6cf4-4de5-9b20-049531501362" - 36 символов, а в базе они сохраняются так: afe171a16cf44de59b20049531501362 - 32 символа.

Это особенность работы поля UUIDField из Django. В MySQL нет поля для UUID, поэтому он хранится в обычном Char и django хранит его там в таком виде (HEX). А при выборке преобразовывает обратно на лету. PostgreSQL поддерживает нативно UUID, и там такая проблема не возникает вообще.
До версии django-1.7 использовалось поле UUIDField из django_extensions. У него логика несколько отличается и поле хранится и обрабатывается как есть: 36 символов. Однако оно объявлено устаревшим и будет удалено, как только прекратится поддержка django 1.7. 
Ну а поскольку в версии 1.x и так уже сломано всё, что можно было сломать, я решил оставить поддержку django_extensions лишь для совместимости с django<1.8.

> Мне кажется, это сломает обратную совместимость в рабочих проектах. 

Вполне вероятно. Но тут, имхо, наиболее верным решением было бы сделать UPDATE всех записей в БД, ссылающихся на UUID, вырезав из них дефисы. И дальше работать как обычно.
Делать обратное с базой ФИАС не выйдет - при очередном обновлении добавятся новые записи с 32-символьными UUID и всё станет ещё хуже (или не станет, но будет каша...).
Ну а уж менять стандартное поведение Django - совсем плохая идея.

> Таблица House. Возможно, нужно добавить индекс для aoguid, как вы считаете?

Изначально я вообще все таблицы связывал через ForeignKey (а к нему индекс добавляется автоматически), но были проблемы с целостностью (PostgreSQL за этим следит внимательно), и база не импортировалась корректно.

Надо бы сделать тестовый прогон с пустыми таблицами и ForeignKey и посмотреть, как с этим обстоят дела сейчас.

Думаю, для поиска домов по aoguid, индекс, конечно же не помешал бы, а ForeignKey был бы лучшим решением. Равно как и прочих объектов.
Попробую потестить это всё, как найду время.

**Comment by Sky-Cat** [comment]
Спасибо за развернутый ответ. Конечно, UUID не так сложно поменять будет.

**Comment by ruid128** [comment]
Добрый день!
В readme указано, что есть версия 2.0.0, но код безнадежно устарел. Возможно, есть отдельный репозиторий с обновленной версией приложения, если приложение поддерживается еще?
