### ISSUE TITLE
Что делать с DEL-таблицами?

### ISSUE THREAD

**Issue by Yuego** [Yuego/django-fias#56]
До сих пор не могу решить, как с ними поступать.
По логике вещей, нужно удалять из БД записи, содержащиеся в этих таблицах.
Но при наличии на них внешних ссылок всё может сломаться.

И я не проверял, но, возможно, там хранятся записи, устаревшие и изменённые (те, что с заполненным полем NEXTID и датой UPDATEDATE из прошлого). Тогда ничего делать и не нужно - в БД хранятся только актуальные версии адресных объектов.

Нужно снова почитать документацию...

**Comment by Yuego** [comment]
Выдержка из документации:

> Дельта данные, т.е. новые, изменившиеся и удаленные данные появившиеся с момента предыдущей выгрузки базы ФИАС, загружаются по следующему алгоритму: по наличию или отсутствию ключа в пользовательской базе определяется тип операции – добавление или обновление записи. **После проведения соответствующих операций необходимо удалить по ключу записи, присутствующие в таблицах, технологически удаленных данных.**

**Comment by jungornti** [comment]
Добрый день.

Представим, что у нас есть база фиас, на которую ссылаются объекты, сайт работает в продакшене.

Если удалять данные из фиас при обновлении, то это может привести к катастрофическим последствиям и к восстановлению базы из бекапа.

Разумным выходом из этой ситуации является такая позиция:

1. ввести понятие «актуальный адрес» (addrobj)
2. дать рекомендации пользователям приложения использовать фильтрацию по актуальным адресам в их приложениях (поиск, добавление и тд). Таким образом, в каждый момент времени можно будет работать только с актуальными записями. А в ситуации, когда объект будет ссылаться на неактуальный адрес (например, если данный адрес не будет обновлён при импорте апдейта) то всё будет работать — это лучше, чем вариант с удалением данных.

Сейчас пользователи могут защититься от этого on_delete=restrict, но тогда это будет вызывать исключения в процесса обновления или импорта, например.

**Comment by Yuego** [comment]
Изучая устройство БД ФИАС, я пришел к выводу, что в таблицах удалённых объектов в большинстве своём находятся записи устаревшие и уже неактуальные (к примеру самый первый предок существующего объекта). 
Для таких случаев вообще никаких действий предпринимать не требуется в силу того, что мы храним только самую актуальную версию каждого объекта.
Вероятность же удаления какого-то объекта совсем очень мала - это надо улицу снести целиком вместе с домами.
Тут нужно добавлять дополнительные проверки, однако "всреднем по больнице", имхо, DEL-таблицы для наших нужд не несут никакой полезной нагрузки, и их можно просто игнорировать.
Но это всё нужно проверять - я могу ошибаться.

**Comment by jungornti** [comment]
По большому счёту — приложение их игнорирует с самого начала, если я правильно понимаю, поэтому скорее всего можно их просто игнорировать. В худшем случае будет рост базы данных со временем из−за устаревших записей, но сейчас стоимость места на диске настолько мала, что проблема будет скорее  всего вообще не заметна с т.з. бизнеса.

**Comment by Yuego** [comment]
Вряд ли сильно много места потеряется в принципе. Для этого должно произойти нечто грандиозное, проде присоединения, а затем отсоединения Крыма :)
Так что на сегодняшний день можно оставить всё как есть и заняться функциями более нужными и полезными.

**Comment by jungornti** [comment]
Согласен, если других возражений нет, можно считать решение принятым и issue закрывать =)
