### ISSUE TITLE
Пример фильтров

### ISSUE THREAD

**Issue by Sky-Cat** [Yuego/django-fias#58]
Подскажите пример фильтров, пожалуйста. Не могу никак разобраться.

Я бы хотел отфильтровать импорт по полю regioncode для таблиц fias_addrobj и fias_house.

Сделал такую функцию:

```
def yaroslavl_addrobj(item):
    """
    Всегда разрешает импорт записи
    :param item:
    :return item or None:
    """
    if item.attrib.get('REGIONCODE') == '76':
      return item
```

Подключил фильтр в файле settings.py:

```
FIAS_TABLE_ROW_FILTERS = [
    'fias1.filters.yaroslavl_addrobj',
]
```

При запуске выдает такую ошибку:

`django.core.exceptions.ImproperlyConfigured: Table row filter module `fias1.filters.yaroslavl_addrobj` does not exists`

**Comment by Yuego** [comment]
Этот функционал экспериментальный и я до сих пор не определился, как же оно должно работать. Потому не тестировал вообще.

Что до вашей проблемы - вы всё делаете верно. Ошибка в самом приложении. Это я поправлю.

**Comment by Yuego** [comment]
Сейчас в этой функции есть одна фундаментальная проблема: все фильтры применяются ко всем таблицам. Если у записи нет поля regioncode, импорт упадёт.

Я думаю, надо разделить их - явно указывать, какой фильтр к какой таблице должен применяться. Это не сложно реализовать.

**Comment by Sky-Cat** [comment]
Спасибо за ответ. Будет замечательно, если у вас получится довести этот функционал до ума. А то я тут загрузил таблицы addrobj и house и стало грустно. Получилось почти 20 гигабайт данных. Причем, в таблице house индексы занимают больше места, чем данные - почти 10 гигабайт.

Поэтому, я думаю, будет очень неплохо фильтровать данные по каким-то критериям, чтобы избыточные данные не загружать.

**Comment by Yuego** [comment]
Тут самая большая проблема - сохранить целостность БД при такой фильтрации.
Хотя с учетом нового алгоритма обработки ошибок, эта функция ложится на саму БД (при условии, что она умеет учитывать ограничения), но импорт замедлится из-за множества попыток добавить записи, у которых нет нужных связей.

**Comment by Sky-Cat** [comment]
Замечание, не относящееся к текущему вопросу. Не стал делать отдельный issue, т. к. это не ошибка.

При первоначальном импорте из dbf архив распаковывается полностью во временную директорию. Если места во временной директории мало (мне, например, не хватило 14 гигабайт), при исчерпании места распаковка прервется.

Импорт из xml ведет себя по-другому: данные все полностью не распаковываются. Видимо, читает пофайлово, что предпочтительнее, конечно.

**Comment by Sky-Cat** [comment]
> но импорт замедлится из-за множества попыток добавить записи, у которых нет нужных связей.

Если фильтровать по regioncode, то самые большие таблицы addrobj и house должны, наверное, быстро импортироваться, т. к. проверка довольно простая. Вот если сложную проверку делать, то долго будет, наверное.

С другой стороны, если человек желает значительно уменьшить размер базы, то скорость импорта тут уже значения иметь не будет.

**Comment by Yuego** [comment]
> Импорт из xml ведет себя по-другому: данные все полностью не распаковываются. Видимо, читает пофайлово, что предпочтительнее, конечно.

Это уже обсуждалось в #44. Думаю, единственным решением здесь будет - добавить ключ для ручного указания каталога временных файлов.

> С другой стороны, если человек желает значительно уменьшить размер базы, то скорость импорта тут уже значения иметь не будет.

Согласен.

**Comment by Sky-Cat** [comment]
> Думаю, единственным решением здесь будет - добавить ключ для ручного указания каталога временных файлов.

Да, это решило бы проблему.

**Comment by Yuego** [comment]
Я загрузил в pypi новый релиз 1.1.2. Фильтры теперь работают индивидуально для каждой таблицы. Пример использования есть в fias/config.py. Я туда ваш фильтр добавил заодно в качестве конкретного примера.

`
FIAS_TABLE_ROW_FILTERS = {
    'addrobj': (
        'fias.importer.filters.example_filter_yaroslavl_region',
    ),
    'house': (
        'fias.importer.filters.example_filter_yaroslavl_region',
    ),
}
`

Список всех доступных таблиц можно найти в том же fias/config.py, а сопоставление их с моделями в fias/importer/table/table.py.

**Comment by Sky-Cat** [comment]
Большое спасибо. Фильтр подключился нормально. Импорт идет уже 5 часов, таблица addrobj довольно быстро отработала. Сейчас работает таблица house. Собственно, она уже около 4 часов обрабатывается. Завтра скажу более точно по срокам.

**Comment by Sky-Cat** [comment]
Импорт шел 5 часов. Но ни одна запись из таблицы house не была внесена. Конец лога:

```
T: house. L: 0 | U: 0 | S: 0[E:0] | R: 0[0]     FN: AS_DEL_HOUSE_20160908_f273ed10-0fae-49dd-8f87-9d3ba2872dab.XML
T: house. L: 0 | U: 0 | S: 45535879[E:0] | R: 0[0]      FN: AS_HOUSE_20160908_d8545d21-e1b0-4a8c-a08e-19aa2366a8fd.XML
T: room. L: 5136 | U: 0 | S: 538938[E:526901] | R: 0[0]         FN: AS_ROOM_20160908_4050aaa0-f451-4312-8f7b-719b8f463f36.XML
Data v.291 from 2016-09-08 loaded at 2016-09-12 17:08:25.153939+00:00
Estimated time: 5:01:26.091623. Download: 0. Unpack: 0. Import: 5:01:25.154523
```

В таблицу room тоже данные не были внесены.

Фильтр для таблиц addrobj и house был такой:
```
def filter_yaroslavl_region(item):
    if item.regioncode == '76':
        return item
```

В конфиге указаны так:
```
FIAS_TABLE_ROW_FILTERS = {
    'addrobj': (
        'fias1.filters.filter_yaroslavl_region',
    ),
    'house': (
        'fias1.filters.filter_yaroslavl_region',
    ),
}
```

Для остальных таблиц фильтры не были настроены.

Таблица addrobj была обработана, более 16 тыс. записей было внесено. Таблица house осталась пустая. Ни одной записи нет. Таблица room тоже пустая.

В таблице fias_status значение ver_id для всех таблиц (и пустых тоже) стоит 291 (я с этой версией настраивал импорт).

Еще интересно поведение таблицы fias_landmark. В нее было внесено только 14 записей, хотя фильтр к ней не применялся. Видимо, идет проверка по внешнему ключу.

**Comment by Sky-Cat** [comment]
Похоже, нашел причину, почему таблица house с фильтром по региону не обрабатывалась. В таблице house поля regioncode быть не должно. По крайней мере, и в полном архиве и в дельте его нет. Это поле при импорте всегда NULL. Соответственно, фильтр по regioncode на таблице house не работает.

Сейчас оставил фильтр только на таблице addrobj и уже есть какие-то данные в таблице house. Точнее скажу после окончания импорта.

**Comment by Yuego** [comment]
> Таблица addrobj была обработана, более 16 тыс. записей было внесено. Таблица house осталась пустая. Ни одной записи нет. Таблица room тоже пустая.

Я проверил на версии 285. Более новую скачать сейчас проблематично, но, думаю, там ситуация будет аналогичной. В общем, в таблице HOUSE поле regioncode не заполнено вообще. 
Из-за этого она и не импортировалась. А таблица ROOM имеет внешний ключ на HOUSE. Как следствие, и она оказалась пустой. Однако, в ROOM поле regioncode оказалось заполненным.

**Comment by Yuego** [comment]
Выходит, БД ФИАС далеко ещё не полна и фильтровать её будет проблематично.

**Comment by Sky-Cat** [comment]
Итак, импорт, наконец, закончился. Долго, конечно, но я очень доволен результатом. Объем уменьшился с 20 гигабайт до 200 мегабайт. Такой результат стоит полутора суток импорта.

Скрин с размером базы: https://im2.yarcom.ru/swfuim.php/get/4224.png

Немного данных:

```
Data v.292 from 2016-09-12 loaded at 2016-09-14 17:42:56.748812+00:00
Estimated time: 1 day, 12:02:49.437269. Download: 0:12:54.917813. Unpack: 0. Import: 1 day, 11:49:53.216748
```

Помимо стандартных таблиц импортировались таблицы:
- house
- room

Фильтр был настроен только на таблицу addrobj, далее уже по цепочке: <- house <- room

Было бы замечательно еще и таблицу normdoc так же фильтровать, но там по внешнему ключу не получится, наверное, т. к. нужно по двум таблицам (addrobj и house) проверять наличие записей. А при импорте таблицы room еще и по ней.

Теперь по скорости. Думаю, можно уменьшить время импорта, если удалить ключи перед импортом, как и предлагается по-умолчанию. Я этого не сделал. На днях попробую без ключей проверить. Еще можно уменьшить размер пачки записей (параметр --limit). Думаю, для фильтров большая пачка будет хуже. Попробую тоже проверить.

**Comment by Sky-Cat** [comment]
Подскажите, пожалуйста, как фильтровать по региону при импорте из dbf-файлов?

Такой фильтр
```
    if item.regioncode == '76':
        return item
```
не работает. Пропускает все записи.
