### ISSUE TITLE
Ошибки при миграции

### ISSUE THREAD

**Issue by nimoism** [Yuego/django-fias#59]
В миграции 0005 зашит путь к fias_xml.rar:
        load_complete_data(path='/home/ego/Downloads/fias_xml.rar', truncate=True, tables=TABLES_STATS)

Так же программная ошибка:

  Applying fias.0005_load_stats_data...Traceback (most recent call last):
....
  File ".../fias/migrations/0005_load_stats_data.py", line 16, in load_stats_data
    fetch_version_info(update_all=True)
  File ".../fias/importer/version.py", line 30, in fetch_version_info
    if not ver.pk or update_all:
UnboundLocalError: local variable 'ver' referenced before assignment

**Comment by Yuego** [comment]
Возможно, у Вас БД не обновится #57.
