### ISSUE TITLE
Документация процесса обновления

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#63]
Добрый день, хотелось бы получить комментарий по поводу обновления базы.

Я посмотрел исходники и обнаружил только такую информацию — адреса только добавляются или обновляются. Получается, что обновление физически не может повредить или удалить связанные объекты, это верно?

И ещё вопрос — я правильно понимаю, что при обновлении определённые адреса могут обновиться и в случае, например, переименования улицы, ссылающиеся объекты автоматически получат корректные адреса по новой улице? Но может быть и ситуация, когда этот объект не будет обновлён и ссылающиеся объекты будут по факту со старым неактуальным адресом?

Может быть стоит отразить этот момент в документации?

**Comment by Yuego** [comment]
> Я посмотрел исходники и обнаружил только такую информацию — адреса только добавляются или обновляются. Получается, что обновление физически не может повредить или удалить связанные объекты, это верно?

Да, всё верно.

> И ещё вопрос — я правильно понимаю, что при обновлении определённые адреса могут обновиться и в случае, например, переименования улицы, ссылающиеся объекты автоматически получат корректные адреса по новой улице? Но может быть и ситуация, когда этот объект не будет обновлён и ссылающиеся объекты будут по факту со старым неактуальным адресом?

Всё зависит исключительно от разработчиков БД ФИАС.
В импортированной базе хранятся только самые последние версии каждого адресного объекта (уникальность по AOGUID, он же - первичный ключ, на который будет ссылка через ForeignKey). В самой ФИАС хранятся все существующие версии каждого объекта.
Соответственно, при обновлении проверяется актуальность объекта (сравниваются даты последнего обновления объекта в БД и импортируемого, а так же проверяется отсутствие у импортируемой записи потомков - пустое поле NEXTID).
Если запись о переименовании объекта добавлена в БД и, соответственно, в дельта-архив, она будет актуализирована.

> Может быть стоит отразить этот момент в документации?

В документацию нужно многое добавить.
Ещё очень хочется переехать на sphinx и оформить доки по-человечески, но пока нет возможности.
Был бы рад любой помощи.

**Comment by jungornti** [comment]
Сделал pull request https://github.com/Yuego/django-fias/pull/65 для ведения документации через sphinx. Так как документация это процесс творческий, я предлагаю Артёму внести основные стилистические правки (порядок разделов, текст, оглавление). А дальше уже и контрибьюторам будет проще документировать.
