### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#64]
Добрый день, при обновлении БД вываливаются вот такие Deprecation Warnings:

Applying fias.0004_auto_20160824_1003... OK
Downloading:  |################################| 100/100. ETA: 1079

fias/importer/indexes.py:43: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  [rel for rel in model._meta.get_all_related_objects() if rel.field_name == field.name]

**Comment by Yuego** [comment]
Пофикшено в #69
